services:

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    env_file:
      - ./config/postgres.example.env
    ports: 
     - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
  denet:
    container_name: denet
    build: 
      context: .  
      dockerfile: Dockerfile
    ports:
        - 8080:8080



volumes:
  pg_data: